### PR TITLE
WINUI-3163-Added the proper UG redirect link for Sfchart

### PR DESCRIPTION
**Pull request by MoneeshramDhanabal**
I have to add the proper UG redirect link for the xamarin forms android sfchart.

### CODE REVIEW

**Comment by MuneeshKumarG** [comment]
rebuild

**Comment by MuneeshKumarG** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Review by MuneeshKumarG — APPROVED** [review]
This is fine

**Review by MuneeshKumarG — APPROVED** [review]
This is fine

**Pull request merged**
